### ISSUE TITLE
asCsv should automatically derive headers from case classes when headers=true

### ISSUE THREAD

**Issue by antonkulaga** [nrinaudo/kantan.csv#161] opened 2018-04-06 00:33 UTC
I've noticed that
```scala
fooObject.asCsv(rfc.withCellSeparator('\t').withHeader(true))
```
does not save case class fields as headers if fooObject is a case class, despite havinng withHeaders(true)

**Comment by nrinaudo** [comment] 2018-04-07 12:33
While absolutely correct, is that not a duplicate of #139 ?

**Closed** 2018-12-08 22:43 UTC
