### ISSUE TITLE
asCsv goes into infinite recursion when certain imports are present

### ISSUE THREAD

**Issue by klaeufer** [nrinaudo/kantan.csv#30] opened 2016-03-17 21:21 UTC
This works:

      $ sbt console
      scala> import kantan.csv.ops._
      scala> List(List(1, 2), List(3, 4)).asCsv(',')
      res0: String =
      "1,2
      3,4
      "

This hangs (and hogs the processor):

      $ sbt console
      scala> import kantan.csv.ops._
      scala> import kantan.csv.generic.codecs._
      scala> List(List(1, 2), List(3, 4)).asCsv(',')

**Comment by nrinaudo** [comment] 2016-03-18 15:10
I've been able to reproduce this with v0.1.8. On the other hand, some (entirely unrelated) changes I've done on v0.1.9 seem to have fixed the issue.

I'll try and publish a snapshot build of v0.1.9 "soon" (hopefully by tonight, more likely over the weekend). If you have the time, would it be possible for you to make sure that the problem is indeed fixed?

**Comment by nrinaudo** [comment] 2016-03-18 16:00
Right, a new snapshot of v0.1.9 is now available and should fix your issue. Would it be possible for you to confirm and, if you're happy with the changed, close the issue?

Note that `kantan.csv.generic.codecs` doesn't exist anymore. Just import `kantan.csv.generic._` instead.

**Comment by nrinaudo** [comment] 2016-04-11 07:26
I'll consider this fixed for now, feel free to reopen if I'm mistaken.

**Closed by nrinaudo** 2016-04-11 07:26 UTC
Labels: bug
