### ISSUE TITLE
Decoding CSV rows with variable lengths fails for case classes

### ISSUE THREAD

**Issue by seanf** [nrinaudo/kantan.csv#184] opened 2019-05-30 02:21 UTC
Issue #53 requested support for variable-length rows, and gave an example of a case class `Foo`.

https://github.com/nrinaudo/kantan.csv/commit/0f027d57edaa102355a18f886a8467f87a543447 shows that variable-length rows work for tuples, but the same test fails if you replace the tuple with Foo:

```scala
    case class Foo(first: Int, second: String, third: Option[Int])

    assert("1,a,100\n2,b\n".unsafeReadCsv[List, Foo](rfc) ==
      List(Foo(1, "a", Some(100)), Foo(2, "b", None))
    )
```

```
Array index out of range: 0
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
	at kantan.csv.CsvSource.$anonfun$unsafeReader$2(CsvSource.scala:96)
	at scala.util.Either$LeftProjection.map(Either.scala:573)
	at kantan.csv.CsvSource.$anonfun$unsafeReader$1(CsvSource.scala:92)
	at kantan.codecs.resource.ResourceIterator$$anon$6.readNext(ResourceIterator.scala:283)
	at kantan.codecs.resource.ResourceIterator.next(ResourceIterator.scala:114)
	at kantan.codecs.resource.ResourceIterator.next$(ResourceIterator.scala:108)
	at kantan.codecs.resource.ResourceIterator$$anon$6.next(ResourceIterator.scala:281)
	at kantan.codecs.resource.ResourceIterator.foreach(ResourceIterator.scala:318)
	at kantan.codecs.resource.ResourceIterator.foreach$(ResourceIterator.scala:318)
	at kantan.codecs.resource.ResourceIterator$$anon$6.foreach(ResourceIterator.scala:281)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:189)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:47)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:313)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:311)
	at kantan.codecs.resource.ResourceIterator$$anon$6.to(ResourceIterator.scala:281)
	at kantan.csv.CsvSource.unsafeRead(CsvSource.scala:153)
	at kantan.csv.CsvSource.unsafeRead$(CsvSource.scala:151)
	at kantan.csv.CsvSource$$anon$1.unsafeRead(CsvSource.scala:232)
	at kantan.csv.ops.CsvSourceOps.unsafeReadCsv(CsvSourceOps.scala:161)
```

**Comment by seanf** [comment] 2019-05-30 04:47
In my use case, I would actually prefer to model the optional value without using `Option` in my case class, perhaps by providing a Decoder/CellDecoder (which would generate a default value if the column is absent), but I'm not sure how I would do that. It would be even better if I could simply put a default value in the case class constructor, eg

```scala
    case class Foo(first: Int, second: String, third: Int = 0)
```

**Comment by nrinaudo** [comment] 2019-05-30 09:23
I can't reproduce your issue. The following compiles and passes:
```scala
    import kantan.csv.ops._

    case class Foo(first: Int, second: String, third: Option[Int])
    implicit val decoder: RowDecoder[Foo] = RowDecoder.ordered(Foo.apply _)


    "1,a,100\n2,b".unsafeReadCsv[List, Foo](rfc) should be(
      List(Foo(1, "a", Some(100)), Foo(2, "b", None))
    )
```

Could you provide your entire code so that I can understand what's going on and, if necessary, fix it?

**Comment by seanf** [comment] 2019-05-30 23:11
@nrinaudo that was the entire body of my test. (I just commented out all the other tests in the file, and nothing changed as it did in https://github.com/nrinaudo/kantan.csv/issues/185.)  I probably should have mentioned that I'm using kantan.csv/generic/codecs/etc _2.12 v0.5.0. 

I had these kantan imports:
```scala
import kantan.codecs.{Decoder, Optional}
import kantan.csv._
import kantan.csv.ops._
import kantan.csv.generic._
```

I see that you've added the ordered `RowDecoder` in your version, which fixes the problem. I hadn't found `RowDecoder.ordered`, so thanks for that!

However, for me at least, the code will still compile without the implicit Decoder, but then it fails at runtime with the `ArrayIndexOutOfBoundsException`). I don't really understand what is happening in that case. 

Is it possible for the Shapeless/generic support to map optional columns to optional case class parameters automatically (assuming the order still matches)?

**Comment by nrinaudo** [comment] 2019-05-31 06:05
That cannot be the entire body of your test. You're not allowed to have assertions at the top level.

I'm happy to try and help with this, but please put in a complete reproduction case.

**Comment by seanf** [comment] 2019-05-31 12:43
By the entire body of the test, I meant the entire body of the test "method", but I don't think I should call it a method since it's more of lambda. Anyway, here's a complete file:

```scala
import kantan.csv._
import kantan.csv.ops._
import kantan.csv.generic._

import org.scalatest.FunSuite

class RegressionTests extends FunSuite {
  test("Trailing optional cells should decode as expected (https://github.com/nrinaudo/kantan.csv/issues/53)") {
    case class Foo(first: Int, second: String, third: Option[Int])

    assert("1,a,100\n2,b\n".unsafeReadCsv[List, Foo](rfc) ==
      List(Foo(1, "a", Some(100)), Foo(2, "b", None))
    )
  }

}
```

Expected result: test passes due to successful parsing and automatic handling of `Option` for the missing value, as with the tuple version.

Actual result:
```
Array index out of range: 0
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
	at kantan.csv.CsvSource.$anonfun$unsafeReader$2(CsvSource.scala:96)
	at scala.util.Either$LeftProjection.map(Either.scala:573)
	at kantan.csv.CsvSource.$anonfun$unsafeReader$1(CsvSource.scala:92)
	at kantan.codecs.resource.ResourceIterator$$anon$6.readNext(ResourceIterator.scala:283)
	at kantan.codecs.resource.ResourceIterator.next(ResourceIterator.scala:114)
	at kantan.codecs.resource.ResourceIterator.next$(ResourceIterator.scala:108)
	at kantan.codecs.resource.ResourceIterator$$anon$6.next(ResourceIterator.scala:281)
	at kantan.codecs.resource.ResourceIterator.foreach(ResourceIterator.scala:318)
	at kantan.codecs.resource.ResourceIterator.foreach$(ResourceIterator.scala:318)
	at kantan.codecs.resource.ResourceIterator$$anon$6.foreach(ResourceIterator.scala:281)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:189)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:47)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:313)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:311)
	at kantan.codecs.resource.ResourceIterator$$anon$6.to(ResourceIterator.scala:281)
	at kantan.csv.CsvSource.unsafeRead(CsvSource.scala:153)
	at kantan.csv.CsvSource.unsafeRead$(CsvSource.scala:151)
	at kantan.csv.CsvSource$$anon$1.unsafeRead(CsvSource.scala:232)
	at kantan.csv.ops.CsvSourceOps.unsafeReadCsv(CsvSourceOps.scala:161)
	at RegressionTests.$anonfun$new$1(RegressionTests.scala:11)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.invokeWithFixture$1(FunSuiteLike.scala:184)
	at org.scalatest.FunSuiteLike.$anonfun$runTest$1(FunSuiteLike.scala:196)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.FunSuiteLike.runTest(FunSuiteLike.scala:196)
	at org.scalatest.FunSuiteLike.runTest$(FunSuiteLike.scala:178)
	at org.scalatest.FunSuite.runTest(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.$anonfun$runTests$1(FunSuiteLike.scala:229)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.FunSuiteLike.runTests(FunSuiteLike.scala:229)
	at org.scalatest.FunSuiteLike.runTests$(FunSuiteLike.scala:228)
	at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
	at org.scalatest.Suite.run(Suite.scala:1147)
	at org.scalatest.Suite.run$(Suite.scala:1129)
	at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.$anonfun$run$1(FunSuiteLike.scala:233)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.FunSuiteLike.run(FunSuiteLike.scala:233)
	at org.scalatest.FunSuiteLike.run$(FunSuiteLike.scala:232)
	at org.scalatest.FunSuite.run(FunSuite.scala:1560)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1346)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1340)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1340)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1031)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1010)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1506)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:131)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
```

**Comment by nrinaudo** [comment] 2019-05-31 12:55
Same was with your other issue, this basically boils down to the fact that you're using the generic module to do your work for you, and the generic module is very strict about what it decodes. If you're not providing exactly the right number of cells in a row, that's not a valid row.

It works for tuples because tuple `RowDecoder` instances are not automatically derived.

**Comment by nrinaudo** [comment] 2019-05-31 12:56
Duplicate of #185

**Closed by nrinaudo** 2019-05-31 12:56 UTC

**Comment by seanf** [comment] 2019-06-03 01:10
> It works for tuples because tuple `RowDecoder` instances are not automatically derived.

I don't understand. It seems like most things are automatically derived when using tuples, particularly `RowDecoder`.

```scala
import kantan.csv._
import kantan.csv.ops._

object DecoderTest extends App {

//  case class CaseClass (
//    num: Int,
//    optionalColumn: Foo = Unknown)
  type CaseClass = (Int, Option[Foo])

  sealed trait Foo
  case object One extends Foo
  case object Two extends Foo
  case object Unknown extends Foo

  implicit val fooDecoder: CellDecoder[Foo] = CellDecoder[Option[String]].map {
    case Some("One") => One
    case Some("Two") => Two
    case _ => Unknown
  }

//  Not needed for tuple: implicit val caseClassDecoder: RowDecoder[CaseClass] = RowDecoder.ordered(CaseClass.apply _)

  val csv =
    """12345
      |12345,One
      |""".stripMargin
  val data = csv.readCsv[Seq, CaseClass](rfc)
  println(data)
}
```

Normally in Scala it seems like case classes are a step up from tuples, with the bonus of names for the type and the properties, but in this case if I switch from a tuple to a case class things become a bit more difficult. I found that a bit [surprising](https://en.wikipedia.org/wiki/Principle_of_least_astonishment), but I guess that just shows my ignorance of Shapeless and/or Scala. ¯\\\_(ツ)\_/¯
